api/urls.py
"""
:Created: 29 May 2016
:Author: Lucas Connors

"""

from django.conf.urls import url

from api.views import CoordinatesFromAddress, DeleteUpdate, PaymentCharge

urlpatterns = [
    url(r"^coordinates/?$", CoordinatesFromAddress.as_view()),
    url(
        r"^payments/charge/(?P<campaign_id>\d+)/?$",
        PaymentCharge.as_view(),
        name="pinax_stripe_charge",
    ),
    url(r"^update/(?P<update_id>\d+)/?$", DeleteUpdate.as_view()),
]

perdiem/urls.py
"""
:Created: 26 July 2015
:Author: Lucas Connors

"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.static import serve

from accounts.views import (
    ContactFormView,
    ProfileView,
    PublicProfileView,
    VerifyEmailView,
    redirect_to_profile,
)
from artist.views import ArtistApplyFormView, ArtistDetailView, ArtistListView
from campaign.views import LeaderboardView
from emails.views import UnsubscribeView, unsubscribe_from_mailchimp
from music.views import AlbumDetailView, MusicListView

urlpatterns = [
    url(r"^health-check/?$", lambda r: HttpResponse(""), name="health_check"),
    url("", include(("social_django.urls", "social"))),
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^api/", include("api.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(
        r"^unsubscribe/from-mailchimp/$",
        unsubscribe_from_mailchimp,
        name="unsubscribe_from_mailchimp",
    ),
    url(
        r"^unsubscribe/(?P<user_id>\d+)/(?P<subscription_type>\w+)/(?P<token>[\w.:\-_=]+)/$",
        UnsubscribeView.as_view(),
        name="unsubscribe",
    ),
    url(
        r"^email/verify/(?P<user_id>\d+)/(?P<code>[\w-]+)/$",
        VerifyEmailView.as_view(),
        name="verify_email",
    ),
    url(r"^payments/", include("pinax.stripe.urls")),
    url(r"^artists/?$", ArtistListView.as_view(), name="artists"),
    url(r"^artist/apply/?$", ArtistApplyFormView.as_view(), name="artist_application"),
    url(
        r"^artist/apply/thanks/?$",
        TemplateView.as_view(template_name="artist/artist_application_thanks.html"),
        name="artist_application_thanks",
    ),
    url(r"^artist/(?P<slug>[\w_-]+)/?$", ArtistDetailView.as_view(), name="artist"),
    url(
        r"^artist/(?P<artist_slug>[\w_-]+)/(?P<album_slug>[\w_-]+)/?$",
        AlbumDetailView.as_view(),
        name="album",
    ),
    url(r"^music/?$", MusicListView.as_view(), name="music"),
    url(r"^profile/?$", ProfileView.as_view(), name="profile"),
    url(
        r"^profile/(?P<username>[\w.@+-]+)/?$",
        PublicProfileView.as_view(),
        name="public_profile",
    ),
    url(r"^stats/?$", LeaderboardView.as_view(), name="leaderboard"),
    url(
        r"^artist-resources/?$",
        TemplateView.as_view(template_name="extra/artist-resources.html"),
        name="artist-resources",
    ),
    url(
        r"^terms/?$",
        TemplateView.as_view(template_name="extra/terms.html"),
        name="terms",
    ),
    url(
        r"^trust/?$",
        TemplateView.as_view(template_name="extra/trust.html"),
        name="trust",
    ),
    url(
        r"^privacy/?$",
        TemplateView.as_view(template_name="extra/privacy.html"),
        name="privacy",
    ),
    url(
        r"^investor-resources/?$",
        TemplateView.as_view(template_name="extra/investor-resources.html"),
        name="investor-resources",
    ),
    url(
        r"^funding/?$",
        TemplateView.as_view(template_name="extra/funding.html"),
        name="funding",
    ),
    url(r"^faq/?$", TemplateView.as_view(template_name="extra/faq.html"), name="faq"),
    url(
        r"^contact/thanks/?$",
        TemplateView.as_view(template_name="registration/contact_thanks.html"),
        name="contact_thanks",
    ),
    url(r"^contact/?$", ContactFormView.as_view(), name="contact"),
    url(r"^$", TemplateView.as_view(template_name="home.html"), name="home"),
    url(r"^(?P<slug>[\w.@+_-]+)/?$", redirect_to_profile),
]

# Add media folder to urls when DEBUG = True
if settings.DEBUG:
    urlpatterns.append(
        url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    )

music/models.py
"""
:Created: 24 July 2016
:Author: Lucas Connors

"""

import boto3
import os
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px 
import matplotlib.pyplot as plt
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from sklearn.metrics import euclidean_distances
from scipy.spatial.distance import cdist
import difflib
from collections import defaultdict
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.metrics import euclidean_distances
from scipy.spatial.distance import cdist
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.manifold import TSNE
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from gfklookupwidget.fields import GfkLookupField
from markdown_deux.templatetags.markdown_deux_tags import markdown_allowed
from pigeon.url.utils import add_params_to_url

from campaign.models import Project


class Album(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    slug = models.SlugField(
        max_length=40,
        db_index=True,
        help_text="A short label for an album (used in URLs)",
    )
    release_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    def validate_unique(self, exclude=None):
        if (
            self.project_id
            and Album.objects.exclude(id=self.id)
            .filter(project__artist=self.project.artist, slug=self.slug)
            .exists()
        ):
            raise ValidationError("Slug must be unique per artist")

    def save(self, *args, **kwargs):
        self.validate_unique()
        super().save(*args, **kwargs)

    def url(self):
        return reverse(
            "album",
            kwargs={"artist_slug": self.project.artist.slug, "album_slug": self.slug},
        )

    def discs(self):
        disc_numbers = (
            self.track_set.all()
            .values_list("disc_number", flat=True)
            .distinct()
            .order_by("disc_number")
        )
        return (
            self.track_set.filter(disc_number=disc).order_by("track_number")
            for disc in disc_numbers
        )

    def total_activity(self, activity_type):
        tracks = self.track_set.all()
        if not tracks:
            return 0

        all_activities = ActivityEstimate.objects.filter(activity_type=activity_type)
        album_events = (
            all_activities.filter(
                content_type=ContentType.objects.get_for_model(self), object_id=self.id
            ).aggregate(total=models.Sum("total"))["total"]
            or 0
        )
        track_events = (
            all_activities.filter(
                content_type=ContentType.objects.get_for_model(tracks[0]),
                object_id__in=tracks.values_list("id", flat=True),
            ).aggregate(total=models.Sum("total"))["total"]
            or 0
        )

        return album_events * tracks.count() + track_events

    def total_downloads(self):
        return self.total_activity(ActivityEstimate.ACTIVITY_DOWNLOAD)

    def total_streams(self):
        return self.total_activity(ActivityEstimate.ACTIVITY_STREAM)


class Track(models.Model):

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    disc_number = models.PositiveSmallIntegerField(default=1)
    track_number = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=60)
    duration = models.DurationField(null=True, blank=True)

    class Meta:
        unique_together = (("album", "disc_number", "track_number"),)

    def __str__(self):
        return "{album} #{track_number}: {name}".format(
            album=str(self.album), track_number=self.track_number, name=self.name
        )

    def total_activity(self, activity_type):
        return (
            ActivityEstimate.objects.filter(
                models.Q(
                    content_type=ContentType.objects.get_for_model(self.album),
                    object_id=self.album.id,
                )
                | models.Q(
                    content_type=ContentType.objects.get_for_model(self),
                    object_id=self.id,
                ),
                activity_type=activity_type,
            ).aggregate(total=models.Sum("total"))["total"]
            or 0
        )

    def total_downloads(self):
        return self.total_activity(ActivityEstimate.ACTIVITY_DOWNLOAD)

    def total_streams(self):
        return self.total_activity(ActivityEstimate.ACTIVITY_STREAM)


class Artwork(models.Model):

    album = models.OneToOneField(Album, on_delete=models.CASCADE)
    img = models.ImageField(upload_to="artist/album")

    class Meta:
        verbose_name_plural = "Artwork"

    def __str__(self):
        return str(self.album)


class AlbumBio(models.Model):

    album = models.OneToOneField(Album, on_delete=models.CASCADE)
    bio = models.TextField(
        help_text="Tracklisting and other info about the album. " + markdown_allowed()
    )

    def __str__(self):
        return str(self.album)


class MarketplaceURL(models.Model):

    MARKETPLACE_ITUNES = "itunes"
    MARKETPLACE_APPLE_MUSIC = "apple"
    MARKETPLACE_CHOICES = (
        ("spotify", "Spotify"),
        (MARKETPLACE_ITUNES, "iTunes"),
        (MARKETPLACE_APPLE_MUSIC, "Apple Music"),
        ("google", "Google Play"),
        ("amazon", "Amazon"),
        ("tidal", "Tidal"),
        ("youtube", "YouTube"),
    )

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    medium = models.CharField(
        choices=MARKETPLACE_CHOICES, max_length=10, help_text="The type of marketplace"
    )
    url = models.URLField(unique=True, help_text="The URL to the album's page")

    class Meta:
        unique_together = (("album", "medium"),)

    def __str__(self):
        return "{album}: {medium}".format(
            album=str(self.album), medium=self.get_medium_display()
        )

    def marketplace_has_affiliate_token(self):
        return self.medium in (self.MARKETPLACE_ITUNES, self.MARKETPLACE_APPLE_MUSIC)

    def affiliate_url(self):
        if self.marketplace_has_affiliate_token() and hasattr(
            settings, "ITUNES_AFFILIATE_TOKEN"
        ):
            return add_params_to_url(self.url, {"at": settings.ITUNES_AFFILIATE_TOKEN})
        return self.url


class S3PrivateFileField(models.FileField):
    def __init__(
        self, verbose_name=None, name=None, upload_to="", storage=None, **kwargs
    ):
        super().__init__(
            verbose_name=verbose_name,
            name=name,
            upload_to=upload_to,
            storage=storage,
            **kwargs,
        )
        self.storage.default_acl = "private"


class Audio(models.Model):

    album = models.OneToOneField(Album, on_delete=models.CASCADE)
    file = S3PrivateFileField(upload_to="artist/audio")

    class Meta:
        verbose_name_plural = "Audio"

    def __str__(self):
        return str(self.album)

    def get_temporary_url(self, ttl=60):
        if hasattr(settings, "AWS_S3_BUCKET_NAME"):
            s3 = boto3.client(
                "s3",
                aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            )
            key = "{media}/{filename}".format(
                media=settings.AWS_S3_KEY_PREFIX, filename=self.file.name
            )
            return s3.generate_presigned_url(
                "get_object",
                Params={"Bucket": settings.AWS_S3_BUCKET_NAME, "Key": key},
                ExpiresIn=ttl,
            )
        return self.file.url


def activity_content_type_choices():
    return {
        "id__in": (
            ContentType.objects.get_for_model(Album).id,
            ContentType.objects.get_for_model(Track).id,
        )
    }


class ActivityEstimate(models.Model):

    ACTIVITY_STREAM = "stream"
    ACTIVITY_DOWNLOAD = "download"
    ACTIVITY_CHOICES = ((ACTIVITY_STREAM, "Stream"), (ACTIVITY_DOWNLOAD, "Download"))

    date = models.DateField(default=timezone.now)
    activity_type = models.CharField(choices=ACTIVITY_CHOICES, max_length=8)
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.PROTECT,
        limit_choices_to=activity_content_type_choices,
    )
    object_id = GfkLookupField("content_type")
    content_object = GenericForeignKey()
    total = models.PositiveIntegerField()

    class Meta:
        unique_together = (("date", "activity_type", "content_type", "object_id"),)

    def __str__(self):
        return str(self.content_object)

class RecommenderSystem(models.Model):

    data = pd.read_csv("C://Users//soham//Downloads//data.csv")
    genre_data = pd.read_csv('C://Users//soham//Downloads//data_by_genres.csv')
    year_data = pd.read_csv('C://Users//soham//Downloads//data_by_year.csv')
    cluster_pipeline = Pipeline([('scaler', StandardScaler()), ('kmeans', KMeans(n_clusters=10))])
    X = genre_data.select_dtypes(np.number)
    cluster_pipeline.fit(X)
    genre_data['cluster'] = cluster_pipeline.predict(X)
    tsne_pipeline = Pipeline([('scaler', StandardScaler()), ('tsne', TSNE(n_components=2, verbose=1))])
    genre_embedding = tsne_pipeline.fit_transform(X)
    projection = pd.DataFrame(columns=['x', 'y'], data=genre_embedding)
    projection['genres'] = genre_data['genres']
    projection['cluster'] = genre_data['cluster']

music/admin/views.py
"""
:Created: 9 October 2016
:Author: Lucas Connors

"""

from django.contrib import messages
from django.urls import reverse

from music.admin.forms import DailyReportForm
from music.models import ActivityEstimate, Track
from perdiem.views import FormsetView


class DailyReportAdminView(FormsetView):

    template_name = "admin/music/activityestimate/daily-report.html"
    form_class = DailyReportForm

    def get_success_url(self):
        return reverse("admin:music_activityestimate_changelist")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "title": "Enter Daily Report",
                "has_permission": self.request.user.is_superuser,
            }
        )
        return context

    def get_formset_factory_kwargs(self):
        num_tracks = Track.objects.all().count()
        return {
            "min_num": num_tracks,
            "max_num": num_tracks,
            "validate_min": True,
            "validate_max": True,
        }

    def get_initial(self):
        tracks = Track.objects.all().order_by("album__project__artist__name", "name")
        return [{"track": track} for track in tracks]

    def formset_valid(self, formset):
        for form in formset:
            d = form.cleaned_data
            track = d["track"]
            num_streams = d["streams"]
            num_downloads = d["downloads"]

            if num_streams:
                ActivityEstimate.objects.create(
                    activity_type=ActivityEstimate.ACTIVITY_STREAM,
                    content_object=track,
                    total=num_streams,
                )
            if num_downloads:
                ActivityEstimate.objects.create(
                    activity_type=ActivityEstimate.ACTIVITY_DOWNLOAD,
                    content_object=track,
                    total=num_downloads,
                )

        messages.success(self.request, "Daily Report was submitted successfully")
        return super().formset_valid(formset)

music/views.py
"""
:Created: 24 July 2016
:Author: Lucas Connors

"""

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from campaign.models import Investment
from music.models import Album


class MusicListView(ListView):

    template_name = "music/music.html"
    context_object_name = "albums"
    model = Album


class AlbumDetailView(TemplateView):

    template_name = "music/album_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        album = get_object_or_404(
            Album,
            slug=kwargs["album_slug"],
            project__artist__slug=kwargs["artist_slug"],
        )

        user = self.request.user
        user_is_investor = (
            user.is_authenticated
            and Investment.objects.filter(
                campaign__project__album=album,
                charge__customer__user=user,
                charge__paid=True,
                charge__refunded=False,
            ).exists()
        )

        context.update({"album": album, "user_is_investor": user_is_investor})
        return context

templates/music/album_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load music %}
{% load humanize %}

{% block socialmeta %}
    <!-- Google+ data -->
    <meta itemprop="name" content="{{ album.name }} by {{ album.project.artist.name }}">
    <meta itemprop="description" content="Discover and invest in music like {{ album.name }} on PerDiem.">
    {% thumbnail album.photo.img "506" as thumb %}
        <meta itemprop="image" content="{{ thumb.url }}">
    {% endthumbnail %}
    <!-- Twitter Card data -->
    {% if album.project.artist.social_twitter %}
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="{{ album.project.artist.social_twitter.username_twitter }}">
        <meta name="twitter:title" content="{{ album.name }} by {{ album.project.artist.name }}">
        <meta name="twitter:description" content="Discover and invest in music like {{ album.name }} on PerDiem.">
        <meta name="twitter:creator" content="{{ album.project.artist.social_twitter.username_twitter }}">
        {% thumbnail album.project.artist.photo.img "208" as thumb %}
            <meta name="twitter:image:src" content="{{ thumb.url }}">
        {% endthumbnail %}
    {% endif %}
    <!-- Open Graph data -->
    <meta property="og:title" content="{{ album.name }} by {{ album.project.artist.name }}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://{{ host }}{% url 'album' artist_slug=album.project.artist.slug album_slug=album.slug %}" />
    {% thumbnail album.photo.img "600" as thumb %}
        <meta property="og:image" content="{{ thumb.url }}" />
        <meta property="og:image:width" content="{{ thumb.width }}" />
        <meta property="og:image:height" content="{{ thumb.height }}" />
    {% endthumbnail %}
    <meta property="og:description" content="Discover and invest in music like {{ album.name }} on PerDiem." />
    <meta property="og:site_name" content="PERDIEM" />
{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "css/music/music.css" %}" type="text/css" charset="utf-8" />
{% endblock %}

{% block content %}
    <h3>{{ album.name }}</h3>
    <h4>BY {{ album.project.artist.name }}</h4>
    <div class="project-image">
        {% thumbnail album.artwork.img "250x250" as thumb %}
            <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="{{ album.name }}" />
        {% endthumbnail %}
    </div>

    {% if user_is_investor %}
        <div class="download-container">
            <a class="button sign-up" href="{{ album.audio.get_temporary_url }}" download>
                DOWNLOAD
            </a>
        </div>
    {% else %}
        <h5>You must be an investor in order to listen and download.</h5>
    {% endif %}
    <div class="break-small">
        <hr>
    </div>
    <div>
        <h4>Streams</h4>
        <h4 class="color-blue">
            {% for disc in album.discs %}
               {% for track in disc %}
                   {{ track.total_streams|intcomma }}{% if not forloop.last %},{% endif %}
               {% endfor %}
               {% if not forloop.last %},{% endif %}
            {% endfor %}
        </h4>
        <p>
            {% for disc in album.discs %}
                {% for track in disc %}
                    {{ track.name }}{% if not forloop.last %},{% endif %}
                {% endfor %}
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        <h4>Downloads</h4>
        <h4 class="color-blue">
            {% for disc in album.discs %}
                {% for track in disc %}
                    {{ track.total_downloads|intcomma }}{% if not forloop.last %},{% endif %}
                {% endfor %}
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </h4>
        <p>
            {% for disc in album.discs %}
                {% for track in disc %}
                   {{ track.name }}{% if not forloop.last %},{% endif %}
               {% endfor %}
               {% if not forloop.last %},{% endif %}
           {% endfor %}
       </p>
    </div>
    <div class="break-small">
        <hr>
    </div>
    <h4>Marketplace</h4>
    <div class="marketplace-container">
        {% for marketplace_url in album.marketplaceurl_set.all %}
            <a href="{{ marketplace_url.url }}" target="_blank">
                {% with "img/marketplace/"|add:marketplace_url.medium|add:".svg" as medium_image %}
                    <img class="marketplace-icons" src="{% static medium_image %}" alt="{{ marketplace_url.get_medium_display }}" />
                {% endwith %}
            </a>
        {% endfor %}
    </div>

    {% if album.release_date %}
        <h4>Released</h4>
        <h6>{{ album.release_date }}</h6>
    {% endif %}

    {% if album.albumbio %}
        <div class="album-bio">
            <p>{{ album.albumbio.bio|markdown }}</p>
        </div>
        <div class="break-small">
            <hr>
        </div>
    {% endif %}
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static "js/vendor/Chart.min.js" %}"></script>
{% endblock %}

templates/music/music.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "css/artist/artist_preview.css" %}" type="text/css" charset="utf-8" />
    <link rel="stylesheet" href="{% static "css/artist/artist_list.css" %}" type="text/css" charset="utf-8" />
{% endblock %}

{% block content %}
    <div id="music-page" class="music-page">
        <h2>Music</h2>
        <div class="break">
            <hr>
        </div>
        <h4>RELEASES AND EXCLUSIVES ON PERDIEM</h4>
        <div class="row small-up-1 medium-up-2 large-up-4 centered artistlist">
            {% for album in albums %}
                <div class="column">
                    <div class="artist-list-image img-list">
                        {% include "object_preview_music.html" with object=album img=album.artwork.img %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}