api/urls.py
"""
:Created: 29 May 2016
:Author: Lucas Connors

"""

from django.conf.urls import url

from api.views import CoordinatesFromAddress, DeleteUpdate, PaymentCharge

urlpatterns = [
    url(r"^coordinates/?$", CoordinatesFromAddress.as_view()),
    url(
        r"^payments/charge/(?P<campaign_id>\d+)/?$",
        PaymentCharge.as_view(),
        name="pinax_stripe_charge",
    ),
    url(r"^update/(?P<update_id>\d+)/?$", DeleteUpdate.as_view()),
]

perdiem/urls.py
"""
:Created: 26 July 2015
:Author: Lucas Connors

"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.static import serve

from accounts.views import (
    ContactFormView,
    ProfileView,
    PublicProfileView,
    VerifyEmailView,
    redirect_to_profile,
)
from artist.views import ArtistApplyFormView, ArtistDetailView, ArtistListView
from campaign.views import LeaderboardView
from emails.views import UnsubscribeView, unsubscribe_from_mailchimp
from music.views import AlbumDetailView, MusicListView

urlpatterns = [
    url(r"^health-check/?$", lambda r: HttpResponse(""), name="health_check"),
    url("", include(("social_django.urls", "social"))),
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^api/", include("api.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(
        r"^unsubscribe/from-mailchimp/$",
        unsubscribe_from_mailchimp,
        name="unsubscribe_from_mailchimp",
    ),
    url(
        r"^unsubscribe/(?P<user_id>\d+)/(?P<subscription_type>\w+)/(?P<token>[\w.:\-_=]+)/$",
        UnsubscribeView.as_view(),
        name="unsubscribe",
    ),
    url(
        r"^email/verify/(?P<user_id>\d+)/(?P<code>[\w-]+)/$",
        VerifyEmailView.as_view(),
        name="verify_email",
    ),
    url(r"^payments/", include("pinax.stripe.urls")),
    url(r"^artists/?$", ArtistListView.as_view(), name="artists"),
    url(r"^artist/apply/?$", ArtistApplyFormView.as_view(), name="artist_application"),
    url(
        r"^artist/apply/thanks/?$",
        TemplateView.as_view(template_name="artist/artist_application_thanks.html"),
        name="artist_application_thanks",
    ),
    url(r"^artist/(?P<slug>[\w_-]+)/?$", ArtistDetailView.as_view(), name="artist"),
    url(
        r"^artist/(?P<artist_slug>[\w_-]+)/(?P<album_slug>[\w_-]+)/?$",
        AlbumDetailView.as_view(),
        name="album",
    ),
    url(r"^music/?$", MusicListView.as_view(), name="music"),
    url(r"^profile/?$", ProfileView.as_view(), name="profile"),
    url(
        r"^profile/(?P<username>[\w.@+-]+)/?$",
        PublicProfileView.as_view(),
        name="public_profile",
    ),
    url(r"^stats/?$", LeaderboardView.as_view(), name="leaderboard"),
    url(
        r"^artist-resources/?$",
        TemplateView.as_view(template_name="extra/artist-resources.html"),
        name="artist-resources",
    ),
    url(
        r"^terms/?$",
        TemplateView.as_view(template_name="extra/terms.html"),
        name="terms",
    ),
    url(
        r"^trust/?$",
        TemplateView.as_view(template_name="extra/trust.html"),
        name="trust",
    ),
    url(
        r"^privacy/?$",
        TemplateView.as_view(template_name="extra/privacy.html"),
        name="privacy",
    ),
    url(
        r"^investor-resources/?$",
        TemplateView.as_view(template_name="extra/investor-resources.html"),
        name="investor-resources",
    ),
    url(
        r"^funding/?$",
        TemplateView.as_view(template_name="extra/funding.html"),
        name="funding",
    ),
    url(r"^faq/?$", TemplateView.as_view(template_name="extra/faq.html"), name="faq"),
    url(
        r"^contact/thanks/?$",
        TemplateView.as_view(template_name="registration/contact_thanks.html"),
        name="contact_thanks",
    ),
    url(r"^contact/?$", ContactFormView.as_view(), name="contact"),
    url(r"^$", TemplateView.as_view(template_name="home.html"), name="home"),
    url(r"^(?P<slug>[\w.@+_-]+)/?$", redirect_to_profile),
]

# Add media folder to urls when DEBUG = True
if settings.DEBUG:
    urlpatterns.append(
        url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    )

artist/models.py
"""
:Created: 12 March 2016
:Author: Lucas Connors

"""

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import escape
from markdown_deux.templatetags.markdown_deux_tags import markdown_allowed

from artist.managers import ArtistQuerySet
from campaign.models import Campaign, Investment


class Genre(models.Model):

    name = models.CharField(max_length=40, db_index=True, unique=True)

    def __str__(self):
        return self.name


class Artist(models.Model):

    name = models.CharField(max_length=60, db_index=True)
    genres = models.ManyToManyField(Genre)
    slug = models.SlugField(
        max_length=40,
        unique=True,
        help_text="A short label for an artist (used in URLs)",
    )
    lat = models.DecimalField(
        max_digits=6,
        decimal_places=4,
        db_index=True,
        help_text="Latitude of artist location",
    )
    lon = models.DecimalField(
        max_digits=7,
        decimal_places=4,
        db_index=True,
        help_text="Longitude of artist location",
    )
    location = models.CharField(
        max_length=40,
        help_text="Description of artist location (usually city, state, country format)",
    )

    objects = ArtistQuerySet.as_manager()

    def __str__(self):
        return self.name

    def url(self):
        return reverse("artist", kwargs={"slug": self.slug})

    def social_twitter(self):
        twitter_socials = self.social_set.filter(medium=Social.SOCIAL_TWITTER)
        if twitter_socials.exists():
            return twitter_socials[0]

    def latest_campaign(self):
        campaigns = Campaign.objects.filter(
            project__artist=self, start_datetime__lt=timezone.now()
        ).order_by("-start_datetime")
        if campaigns:
            return campaigns[0]

    def active_campaign(self):
        active_campaigns = (
            Campaign.objects.filter(
                project__artist=self, start_datetime__lt=timezone.now()
            )
            .filter(
                models.Q(end_datetime__isnull=True)
                | models.Q(end_datetime__gte=timezone.now())
            )
            .order_by("-start_datetime")
        )
        if active_campaigns:
            return active_campaigns[0]

    def past_campaigns(self):
        return Campaign.objects.filter(
            project__artist=self, end_datetime__lt=timezone.now()
        ).order_by("-end_datetime")

    def all_campaigns_failed(self):
        # Artists that have an active campaign have not failed
        if self.active_campaign():
            return False

        # Artists that have no past campaigns have not failed
        past_campaigns = self.past_campaigns()
        if not past_campaigns:
            return False

        # Check all of the artist's past campaigns to see if any of them succeeded
        for campaign in past_campaigns:
            if campaign.percentage_funded() == 100:
                return False
        return True

    def has_permission_to_submit_update(self, user):
        return user.is_authenticated and (
            user.is_superuser or self.artistadmin_set.filter(user=user).exists()
        )

    def is_investor(self, user):
        return Investment.objects.filter(
            charge__customer__user=user, campaign__project__artist=self
        ).exists()

    def investors(self):
        investors = {}
        for project in self.project_set.all():
            investors = project.project_investors(investors=investors)
        return investors


class ArtistAdmin(models.Model):

    ROLE_MUSICIAN = "musician"
    ROLE_MANAGER = "manager"
    ROLE_PRODUCER = "producer"
    ROLE_SONGWRITER = "songwriter"
    ROLE_CHOICES = (
        (ROLE_MUSICIAN, "Musician"),
        (ROLE_MANAGER, "Manager"),
        (ROLE_PRODUCER, "Producer"),
        (ROLE_SONGWRITER, "Songwriter"),
    )

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(
        choices=ROLE_CHOICES,
        max_length=12,
        help_text="The relationship of this user to the artist",
    )

    def __str__(self):
        return str(self.user)


class Bio(models.Model):

    artist = models.OneToOneField(Artist, on_delete=models.CASCADE)
    bio = models.TextField(help_text="Short biography of artist. " + markdown_allowed())

    def __str__(self):
        return str(self.artist)


class Photo(models.Model):

    artist = models.OneToOneField(Artist, on_delete=models.CASCADE)
    img = models.ImageField(
        upload_to="artist", help_text="Primary profile photo of artist"
    )

    def __str__(self):
        return str(self.artist)


class Playlist(models.Model):

    PLAYLIST_PROVIDER_SPOTIFY = "spotify"
    PLAYLIST_PROVIDER_SOUNDCLOUD = "soundcloud"
    PLAYLIST_PROVIDER_CHOICES = (
        (PLAYLIST_PROVIDER_SPOTIFY, "Spotify"),
        (PLAYLIST_PROVIDER_SOUNDCLOUD, "SoundCloud"),
    )

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    provider = models.CharField(
        choices=PLAYLIST_PROVIDER_CHOICES,
        max_length=10,
        help_text="Provider of the playlist",
    )
    uri = models.TextField(
        help_text="URI that with the provider uniquely identifies a playlist"
    )

    class Meta:
        unique_together = (("provider", "uri"),)

    def __str__(self):
        return self.uri

    def html(self):
        if self.provider == self.PLAYLIST_PROVIDER_SOUNDCLOUD:
            return """
                <iframe width="100%" height="166" scrolling="no" frameborder="no"
                    src="https://w.soundcloud.com/player/?url={url}&color=ff5500"
                >
                </iframe>
            """.format(
                url=self.uri
            )
        elif self.provider == self.PLAYLIST_PROVIDER_SPOTIFY:
            return """
                <iframe src="https://embed.spotify.com/?uri={uri}&theme=white" width="300" height="80" frameborder="0"
                    allowtransparency="true"
                >
                </iframe>
            """.format(
                uri=self.uri
            )


class Social(models.Model):

    SOCIAL_TWITTER = "twitter"
    SOCIAL_CHOICES = (
        ("facebook", "Facebook"),
        (SOCIAL_TWITTER, "Twitter"),
        ("instagram", "Instagram"),
        ("youtube", "YouTube"),
        ("soundcloud", "SoundCloud"),
    )

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    medium = models.CharField(
        choices=SOCIAL_CHOICES, max_length=10, help_text="The type of social network"
    )
    url = models.URLField(
        unique=True, help_text="The URL to the artist's social network page"
    )

    class Meta:
        unique_together = (("artist", "medium"),)

    def __str__(self):
        return "{artist}: {medium}".format(
            artist=str(self.artist), medium=self.get_medium_display()
        )

    def username_twitter(self):
        if self.medium == self.SOCIAL_TWITTER:
            return "@{username}".format(username=self.url.split("/")[-1])
        return self.url


class Update(models.Model):

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    created_datetime = models.DateTimeField(db_index=True, auto_now_add=True)
    title = models.CharField(max_length=75)
    text = models.TextField(
        help_text="The content of the update. " + markdown_allowed()
    )

    def __str__(self):
        return self.title


class UpdateImage(models.Model):

    update = models.ForeignKey(Update, on_delete=models.CASCADE)
    img = models.ImageField(upload_to="/".join(["artist", "updates"]))

    def __str__(self):
        return str(self.update)


class UpdateMediaURL(models.Model):

    MEDIA_YOUTUBE = "youtube"
    MEDIA_CHOICES = ((MEDIA_YOUTUBE, "YouTube"),)

    update = models.ForeignKey(Update, on_delete=models.CASCADE)
    media_type = models.CharField(choices=MEDIA_CHOICES, max_length=8)
    url = models.URLField()

    def __str__(self):
        return str(self.update)

    def clean_youtube_url(self):
        url = escape(self.url)

        # A hack to correct youtu.be links and normal watch links into embed links
        # TODO: Make more robust using regex and getting all query parameters
        if "youtu.be/" in url:
            url = url.replace("youtu.be/", "youtube.com/watch?v=")
        return url

    def thumbnail_html(self):
        if self.media_type == self.MEDIA_YOUTUBE:
            url = self.clean_youtube_url().replace("www.youtube.com", "youtube.com")
            thumbnail_url = "{base}/hqdefault.jpg".format(
                base=url.replace("youtube.com/watch?v=", "img.youtube.com/vi/")
            )
            return '<a href="{url}"><img src="{thumbnail_url}" /></a>'.format(
                url=url, thumbnail_url=thumbnail_url
            )

    def embed_html(self):
        if self.media_type == self.MEDIA_YOUTUBE:
            url = self.clean_youtube_url().replace("/watch?v=", "/embed/")
            return """
                <div class="videowrapper">
                    <iframe width="560" height="315" src="{url}" frameborder="0" allowfullscreen></iframe>
                </div>
            """.format(
                url=url
            )

artist/forms.py
"""
:Created: 19 March 2016
:Author: Lucas Connors

"""

from django import forms
from pagedown.widgets import PagedownWidget


class ArtistApplyForm(forms.Form):

    artist_name = forms.CharField(label="Artist / Band Name")
    photo_link = forms.URLField(
        label="Artist Profile Photo (Download URL)",
        widget=forms.TextInput(attrs={"placeholder": "http://"}),
    )
    genre = forms.CharField()
    location = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField()
    bio = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "We started playing music because..."}
        )
    )
    project = forms.CharField(
        label="Project Name",
        widget=forms.TextInput(attrs={"placeholder": "Single/Album Name"}),
    )
    campaign_reason = forms.CharField(
        label="What are you raising money for?",
        widget=forms.Textarea(
            attrs={"placeholder": "We are raising money to promote our album..."}
        ),
    )
    amount_raising = forms.CharField(
        label="Amount Raising", widget=forms.TextInput(attrs={"placeholder": "$1,000"})
    )
    giving_back = forms.CharField(
        label="% Back To Investors",
        widget=forms.TextInput(attrs={"placeholder": "50%"}),
    )
    campaign_start = forms.DateField(
        label="Campaign Start Date",
        widget=forms.TextInput(attrs={"placeholder": "MM/DD/YYYY"}),
    )
    campaign_end = forms.DateField(
        label="Campaign End Date",
        widget=forms.TextInput(attrs={"placeholder": "MM/DD/YYYY"}),
    )
    payback_period = forms.CharField(
        label="How long you want to pay back investors",
        widget=forms.TextInput(attrs={"placeholder": "5 years, 10 years, 20 years..."}),
    )
    soundcloud = forms.URLField(
        label="SoundCloud", widget=forms.TextInput(attrs={"placeholder": "http://"})
    )
    spotify = forms.URLField(
        required=False,
        label="Spotify",
        widget=forms.TextInput(attrs={"placeholder": "http://"}),
    )
    facebook = forms.URLField(
        required=False, widget=forms.TextInput(attrs={"placeholder": "http://"})
    )
    twitter = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"placeholder": "@"})
    )
    instagram = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"placeholder": "@"})
    )
    terms = forms.BooleanField(
        label="Terms & Conditions",
        help_text="I have read and agree to the Terms & Conditions",
    )


class ArtistUpdateForm(forms.Form):

    title = forms.CharField(max_length=75)
    text = forms.CharField(widget=PagedownWidget())
    image = forms.ImageField(required=False)
    youtube_url = forms.URLField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        image = cleaned_data["image"]
        youtube_url = cleaned_data["youtube_url"]
        provided = list(filter(lambda x: x, [image, youtube_url]))
        if len(provided) > 1:
            raise forms.ValidationError("Please only provide one image or video.")
        return cleaned_data

templates/artist/includes/artist_current_project.html
{% load humanize %}
{% load perdiem %}

<h3>Current Project</h3>
<div class="profile-container">
    <canvas id="myChart5"></canvas>
</div>
<ul>
    {% if user_investor %}
        <li class="me-investing">
            My percentage:
            {% if user_investor.percentage < 0.005 %}
                &lt;0.01%
            {% else %}
                {{ user_investor.percentage|notrail_floatformat:2 }}%
            {% endif %}
        </li>
    {% endif %}
    {% for percentage_breakdown in campaign.project.artist_percentage %}
        <li>{{ percentage_breakdown.name }}: {{ percentage_breakdown.percentage|notrail_floatformat:2 }}%</li>
    {% endfor %}
    <li>
        {% if user_investor %}Other Investors:{% else %}Investors:{% endif %}
        {{ fans_percentage|notrail_floatformat:2 }}%
    </li>
</ul>

templates/artist/includes/artist_detail_invest.html
{% load staticfiles %}
{% load humanize %}
{% load perdiem %}

<div class="tabs-panel" id="invest">
    {% if user.is_authenticated %}
        <h3>Invest in {{ campaign.project.reason }}</h3>
        <div class="break">
            <hr>
        </div>
        {% include "artist/includes/invest.html" %}
    {% else %}
        <h4>To Invest in {{ artist.name }}</h4>
        {% include "artist/includes/auth_buttons.html" %}
    {% endif %}

    <div class="break">
        <hr>
    </div>

    <h4>CURRENT INVESTORS</h4>
    <ul class="menu vertical nested is-active">
        {% for investor in investors %}
            <li id="investor-block">
                {% if investor.public_profile_url %}
                    <a href="{{ investor.public_profile_url }}">
                        <img class="profile-crop-list" src="{{ investor.avatar_url }}" alt="{{ investor.name }}" />
                        <br/>{{ investor.name }}
                {% else %}
                    {{ investor.name }}
                {% endif %}
                {% if investor.public_profile_url %}
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

</div>

templates/artist/includes/artist_detail_overview.html
{% load humanize %}
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load perdiem %}

<div class="tabs-panel {% if not form.errors %}is-active{% endif %}" id="overview">

    <!-- Photo -->
    {% thumbnail artist.photo.img "500x500" as thumb %}
        <div class="photo-left">
            <img class="dropshadow" src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="{{ artist.name }}" />
        </div>
    {% endthumbnail %}

    <!-- Genre -->
    {% with genres=artist.genres.all %}
        <h4 class="strong">
            {{ genres|length|pluralize }} {{ genres|join:" / " }}
            // {{ artist.location }}
        </h4>
    {% endwith %}

    {% if artist.playlist_set.exists %}
        <div class="artist-detail-padding">
            {% for playlist in artist.playlist_set.all %}
                {{ playlist.html|safe }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="break">
        <hr>
    </div>

    <!-- Bio -->
    {% if artist.bio %}
        <div class="artist-detail-padding">
            {{ artist.bio.bio|markdown:'trusted' }}
        </div>
    {% endif %}

    <!-- Socials -->
    {% for social in artist.social_set.all %}
        <a href="{{ social.url }}"><i class="fa fa-{{ social.get_medium_display|lower }} fa-2x social-padding" aria-hidden="true"></i></a>
    {% endfor %}
    <div class="break">
        <hr>
    </div>
</div>

templates/artist/includes/artist_detail_projects.html
{% load staticfiles %}
{% load humanize %}
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load perdiem %}
{% load music %}

<div class="tabs-panel" id="projects">
    {% if campaign %}
        {% include "artist/includes/artist_current_project.html" %}
    {% endif %}
    {% if latest_campaign and latest_campaign.project.generated_revenue %}
        <br/>
        <h5>
            ${{ latest_campaign.project.generated_revenue|notrail_floatformat:2|intcomma }}
            generated so far from this project
            (${{ latest_campaign.project.generated_revenue_fans|notrail_floatformat:2|intcomma }}
            for investors).
        </h5>
        <div class="break">
            <hr>
        </div>
    {% endif %}
    {% include "artist/includes/artist_past_campaigns.html" %}
</div>

templates/artist/includes/artist_detail_updates.html
<div class="tabs-panel {% if form.errors %}is-active{% endif %}" id="updates">
    {% if user.is_authenticated %}
        {% if updates or has_permission_to_submit_update %}
            <h3>LATEST HAPPENINGS</h3>
            {% include "artist/includes/artist_updates.html" with updates=updates has_permission_to_submit_update=has_permission_to_submit_update %}
            {% if has_permission_to_submit_update %}
                <h2>POST AN UPDATE</h2>
                <form action="" method="POST" enctype="multipart/form-data" class="update-container">
                    {% csrf_token %}
                    <ul class="tabs" data-tabs id="artist-update-form-media-tabs">
                        <li class="tabs-title is-active"><a href="#image" aria-selected="true"><i class="fa fa-picture-o fa-2x tab-icon" aria-hidden="true"></i><span class="artist-tab">Photo</span></a></li>
                        <li class="tabs-title"><a href="#video"><i class="fa fa-video-camera fa-2x tab-icon" aria-hidden="true"></i><span class="artist-tab">Video</span></a></li>
                    </ul>

                    <div class="tabs-content" data-tabs-content="artist-update-form-media-tabs">
                        <div class="tabs-panel is-active" id="image">
                            <p>
                                {{ form.image.errors }}
                                {{ form.image.label }}:
                                {{ form.image }}
                            </p>
                        </div>
                        <div class="tabs-panel" id="video">
                            <p>
                                {{ form.youtube_url.errors }}
                                {{ form.youtube_url.label }}:
                                {{ form.youtube_url }}
                            </p>
                        </div>
                        <p>{{ form.non_field_errors }}</p>
                        <p>
                            {{ form.title.errors }}
                            {{ form.title.label }}:
                            <span class="textbox">{{ form.title }}</span>
                        </p>
                        <p>
                            {{ form.text.errors }}
                            {{ form.text.label }}:
                            {{ form.text }}
                        </p>
                    </div>
                    <input type="submit" value="Submit" />
                </form>
            {% endif %}
        {% else %}
            <p>This is where artists will share their updates.</p>
            <p>Looks like they haven't posted yet, but when they do you'll see them right here</p>
        {% endif %}
    {% else %}
        <h4>To View Updates</h4>
        {% include "artist/includes/auth_buttons.html" %}
    {% endif %}
</div>

templates/artist/includes/artist_past_campaigns.html
{% load staticfiles %}
{% load humanize %}
{% load perdiem %}

<h3>Past Campaigns</h3>
<ul>
    {% for past_campaign in artist.past_campaigns %}
        <div class="past-campaign">
            <div class="break">
                <hr>
            </div>
            <li>
                <div class="project-artwork">
                    <h6 class="project-details">{{ past_campaign.project.reason }}</h6>
                </div>
                <h5 class="extra-padding strong">Raised ${{ past_campaign.amount|intcomma }} for {{ past_campaign.fans_percentage }}% of {{ past_campaign.project.reason }} revenue</h5>
                <h6>{{ past_campaign.use_of_funds }}</h6>
                {% if past_campaign.project.generated_revenue %}
                    <h6>${{ past_campaign.project.generated_revenue|notrail_floatformat:2|intcomma }} generated so far from this project</h6>
                    <h6>${{ past_campaign.project.generated_revenue_fans|notrail_floatformat:2|intcomma }} for investors</h6>
                {% endif %}
                <div class="break">
                    <hr>
                </div>
            </li>
        </div>
    {% endfor %}
</ul>

templates/artist/includes/artist_update_media.html
{% load thumbnail %}

{% for media_url in update.updatemediaurl_set.all %}
    {% if not forloop.first %}<br />{% endif %}
    {% if embed %}
        {{ media_url.embed_html|safe }}
    {% else %}
        {{ media_url.thumbnail_html|safe }}
    {% endif %}
{% endfor %}
{% for image in update.updateimage_set.all %}
    {% if not forloop.first %}<br />{% endif %}
    {% thumbnail image.img "500x500" as thumb %}
        <img src="{{ thumb.url }}" alt="{{ update.title }}" />
    {% endthumbnail %}
{% endfor %}

templates/artist/includes/artist_updates.html
{% load markdown_deux_tags %}

<div class="update-container">
    <ul class="menu vertical nested is-active updates">
        {% for update in updates %}
                <li id="update-{{ update.id }}">
                    <div class="break">
                        <hr>
                    </div>
                    {% if show_artist_name %}
                        <h3>{{ update.artist.name }}</h3>
                    {% endif %}
                    <h4>
                        {{ update.title }}
                        {% if has_permission_to_submit_update %}
                            <button id="update-{{ update.id }}" class="button delete-update"><i class="fa fa-trash"></i></button>
                        {% endif %}
                    </h4>
                    {% include "artist/includes/artist_update_media.html" with update=update embed=True %}
                    <p><small>[{{ update.created_datetime }}]</small></p>
                    <p>{{ update.text|markdown }}</p>
                </li>
        {% endfor %}
    </ul>
</div>

templates/artist/includes/auth_buttons.html
<a class="button login-box" href="{% url 'register' %}?next={{ request.get_full_path }}">SIGN UP</a>
<button class="button login-box" data-open="login-modal">LOGIN</button>

templates/artist/includes/investor_profile_artist_list.html
{% load staticfiles %}
{% load humanize %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "css/artist/artist_list.css" %}" type="text/css" charset="utf-8" />
{% endblock %}

<div class="row small-up-1 medium-up-2 large-up-4 centered artistlist">
    {% for artist in artists.values %}
        <div class="column">
            <div class="artist-list-image img-list">
                {% include "object_preview.html" with object=artist img=artist.photo.img %}
            </div>
            {% if show_earnings %}
                <div>
                    <p class="green-color">
                        {% if artist.total_earned %}
                            <i class="fa fa-arrow-up" aria-hidden="true"></i>
                        {% endif %}
                        ${{ artist.total_earned|floatformat:2|intcomma }} /
                        <span class="color-grey">${{ artist.total_invested|floatformat:2|intcomma }}</span>
                    </p>
                </div>
            {% endif %}
        </div>
    {% endfor %}
</div>